clc;
clear all; 
close all;

 

% mex -L. -I"/home/chuongnguyen/Documents/Dropbox/SubCodes/Eigen334"...
%     -largeArrayDims...
%     solver_eigen_mex.cpp
% 
% mex -L. -I"/home/chuongnguyen/Documents/Dropbox/SubCodes/Eigen334"...
%     -largeArrayDims...
%     itera_solver_eigen_lhs_vector_mex.cpp

mex -L. -I"/usr/include/eigen3" -L/usr/lib64 -lpastix -lscotch -lscotcherr ...
    -largeArrayDims...
    solver_pastix_mex.cpp